"""Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms."""

import time

t0 = time.time()

# initialize fib sequence
fib1 = 1
fib2 = 2

# store our answer here
ans = 0

# run the loop
while fib1 < 4000000:
    # we will be looking at fib2 to add to our ans
    if fib2 % 2 == 0:
        ans += fib2

    # create a temp variable, and update as per fib
    temp = fib1
    fib1 = fib2
    fib2 = temp + fib2

print(ans)

t1 = time.time()
print("Execution time: " + str(t1 - t0) + " seconds.")